### ISSUE TITLE
JHU atlas: coronal and axial labels are swapped

### ISSUE THREAD

**Issue by epongpipat** [LCBC-UiO/ggsegExtra#3]
`ggseg(atlas = "jhu", mapping = aes(fill = area))`

![image](https://user-images.githubusercontent.com/26448234/58994413-0178c380-87b6-11e9-8ac5-3534a7a58ca9.png)

**Comment by epongpipat** [comment]
I tried to correct this in the jhu.rda file so that I could push the change but noticed there was a jhu.R that read from geobrain_JHU.rda and wasn't sure if this file was used to make the jhu.rda?

**Comment by Athanasiamo** [comment]
Hi! This is me, I always mix those planes up. My brain always thinks coronal is axial (because I think of a crown), and I just cant seem to get it straight! Anyway, I believe new axis labels should now be fixed with the newest merge, for jhu and tracula.

**Comment by epongpipat** [comment]
I just downloaded the latest versions of `ggseg` and `ggsegExtra`, and it's still showing the same result for me.

**Comment by Athanasiamo** [comment]
sorry about. Forgot one more place it needed to change. Please try the newest version of 
ggsegExtra again.

![image](https://user-images.githubusercontent.com/14014329/59560283-c7a68900-900f-11e9-967b-931fabd311a6.png)

**Comment by epongpipat** [comment]
Perfect! Thank you!
